// Cloudflare R2 storage — S3-compatible API. Documents (originals + compressed
// versions) live in a private bucket; access goes through short-lived presigned
// URLs generated by the API routes. If the env vars are not set, isConfigured()
// returns false and every caller falls back to the legacy Postgres-bytes path,
// so the app keeps working before credentials are pasted in.
import { S3Client, PutObjectCommand, GetObjectCommand, DeleteObjectCommand } from "@aws-sdk/client-s3";
import { getSignedUrl } from "@aws-sdk/s3-request-presigner";

const ACCOUNT_ID = process.env.R2_ACCOUNT_ID ?? "";
const ACCESS_KEY_ID = process.env.R2_ACCESS_KEY_ID ?? "";
const SECRET_ACCESS_KEY = process.env.R2_SECRET_ACCESS_KEY ?? "";
const BUCKET = process.env.R2_BUCKET ?? "";

/** True when all four R2 env vars are present — gates every storage decision. */
export function r2Configured(): boolean {
    return !!(ACCOUNT_ID && ACCESS_KEY_ID && SECRET_ACCESS_KEY && BUCKET);
}

let client: S3Client | null = null;
function s3(): S3Client {
    if (!client) {
        client = new S3Client({
            region: "auto",
            endpoint: `https://${ACCOUNT_ID}.r2.cloudflarestorage.com`,
            credentials: { accessKeyId: ACCESS_KEY_ID, secretAccessKey: SECRET_ACCESS_KEY },
        });
    }
    return client;
}

/** Upload a buffer. Returns the storage key used. */
export async function r2Put(key: string, body: Buffer, contentType: string): Promise<void> {
    await s3().send(new PutObjectCommand({ Bucket: BUCKET, Key: key, Body: body, ContentType: contentType }));
}

/** Fetch the object bytes (server-side use, e.g. compression or legacy migration). */
export async function r2Get(key: string): Promise<{ body: Buffer; contentType: string | undefined }> {
    const res = await s3().send(new GetObjectCommand({ Bucket: BUCKET, Key: key }));
    const bytes = await res.Body?.transformToByteArray();
    return { body: Buffer.from(bytes ?? []), contentType: res.ContentType };
}

/** Delete an object (best-effort — failures ignored so DB cleanup never blocks). */
export async function r2Delete(key: string): Promise<void> {
    try {
        await s3().send(new DeleteObjectCommand({ Bucket: BUCKET, Key: key }));
    } catch { }
}

/**
 * Presigned GET URL the browser can use directly (preview inline or download).
 * expirySeconds default 15 minutes; inline=true renders in the browser,
 * inline=false forces a download with the given filename.
 */
export async function r2PresignGet(key: string, opts?: { expirySeconds?: number; inline?: boolean; fileName?: string }): Promise<string> {
    const expiry = opts?.expirySeconds ?? 15 * 60;
    const disposition = opts?.inline === false
        ? `attachment; filename="${encodeURIComponent(opts?.fileName ?? "document")}"`
        : "inline";
    const cmd = new GetObjectCommand({
        Bucket: BUCKET,
        Key: key,
        ResponseContentDisposition: disposition,
    });
    return getSignedUrl(s3(), cmd, { expiresIn: expiry });
}

/** Canonical key layout: cases/{caseId}/{docId}/{timestamp}-{safeName}[.variant] */
export function docKey(caseId: number, docId: number, fileName: string, variant?: "compressed" | "converted" | "merged" | "zip"): string {
    const safe = fileName.replace(/[^a-zA-Z0-9._-]+/g, "-").slice(-120) || "file";
    const ts = new Date().toISOString().replace(/[-:T]/g, "").slice(0, 14);
    return variant
        ? `cases/${caseId}/${docId}/${ts}-${safe}.${variant}`
        : `cases/${caseId}/${docId}/${ts}-${safe}`;
}

/** Canonical key layout for staff chat attachments: staff-chat/{roomId}/{timestamp}-{rand}-{safeName} */
export function staffDocKey(roomId: number, fileName: string): string {
    const safe = fileName.replace(/[^a-zA-Z0-9._-]+/g, "-").slice(-120) || "file";
    const ts = new Date().toISOString().replace(/[-:T]/g, "").slice(0, 14);
    const rand = Math.random().toString(36).substring(2, 8);
    return `staff-chat/${roomId}/${ts}-${rand}-${safe}`;
}