-- =============================================================================
-- Phase 1 — Service lines & products (HFMC multi-service migration)
--
-- GENERATED by scripts/phase1-gen-sql.cjs via `prisma migrate diff
-- --from-url <live db> --to-schema-datamodel prisma/schema.prisma --script`.
--
-- WHY NOT `prisma migrate dev`: this repo has NO migration history
-- (prisma/migrations has no migration_lock.toml — the database was created with
-- `prisma db push`). migrate dev therefore reports drift and offers to RESET
-- the public schema, which would DROP every table and lose all data. Never run
-- it against this database; use the diff + db execute path instead.
--
-- SCOPE: purely additive. New tables ServiceLine / Product / Lead / StageSet,
-- plus nullable serviceLineId / productId / stageSetId / legStatus columns on
-- existing tables. No existing column is dropped, renamed or retyped, and no
-- existing row is modified — so the app keeps working unchanged even if the
-- backfill script below is never run.
-- =============================================================================

-- AlterTable
ALTER TABLE "CommTemplate" ADD COLUMN     "serviceLineId" INTEGER;

-- AlterTable
ALTER TABLE "DocRule" ADD COLUMN     "serviceLineId" INTEGER;

-- AlterTable
ALTER TABLE "LoanCase" ADD COLUMN     "decidedAt" TIMESTAMP(3),
ADD COLUMN     "decidedById" INTEGER,
ADD COLUMN     "legStatus" TEXT NOT NULL DEFAULT 'Active',
ADD COLUMN     "productId" INTEGER,
ADD COLUMN     "serviceLineId" INTEGER;

-- AlterTable
ALTER TABLE "SlaRule" ADD COLUMN     "serviceLineId" INTEGER;

-- AlterTable
ALTER TABLE "StageItem" ADD COLUMN     "stageSetId" INTEGER;

-- CreateTable
CREATE TABLE "ServiceLine" (
    "id" SERIAL NOT NULL,
    "code" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "shortName" TEXT NOT NULL DEFAULT '',
    "active" BOOLEAN NOT NULL DEFAULT true,
    "sortOrder" INTEGER NOT NULL DEFAULT 0,
    "bankRaced" BOOLEAN NOT NULL DEFAULT false,
    "notes" TEXT NOT NULL DEFAULT '',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ServiceLine_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Product" (
    "id" SERIAL NOT NULL,
    "serviceLineId" INTEGER NOT NULL,
    "code" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "active" BOOLEAN NOT NULL DEFAULT true,
    "sortOrder" INTEGER NOT NULL DEFAULT 0,
    "notes" TEXT NOT NULL DEFAULT '',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Product_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Lead" (
    "id" SERIAL NOT NULL,
    "fullName" TEXT NOT NULL,
    "phone" TEXT NOT NULL DEFAULT '',
    "email" TEXT,
    "serviceLineId" INTEGER NOT NULL,
    "productId" INTEGER,
    "intendedAmount" INTEGER,
    "currency" TEXT NOT NULL DEFAULT 'AED',
    "source" TEXT NOT NULL DEFAULT 'Direct',
    "sourceDetail" TEXT NOT NULL DEFAULT '',
    "status" TEXT NOT NULL DEFAULT 'New',
    "ownerId" INTEGER,
    "clientId" INTEGER,
    "caseId" INTEGER,
    "lostReason" TEXT NOT NULL DEFAULT '',
    "firstContactedAt" TIMESTAMP(3),
    "convertedAt" TIMESTAMP(3),
    "convertedById" INTEGER,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Lead_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "StageSet" (
    "id" SERIAL NOT NULL,
    "serviceLineId" INTEGER NOT NULL,
    "name" TEXT NOT NULL,
    "active" BOOLEAN NOT NULL DEFAULT true,
    "sortOrder" INTEGER NOT NULL DEFAULT 0,
    "isDefault" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "StageSet_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "ServiceLine_code_key" ON "ServiceLine"("code");

-- CreateIndex
CREATE INDEX "ServiceLine_active_sortOrder_idx" ON "ServiceLine"("active", "sortOrder");

-- CreateIndex
CREATE UNIQUE INDEX "Product_code_key" ON "Product"("code");

-- CreateIndex
CREATE INDEX "Product_serviceLineId_active_sortOrder_idx" ON "Product"("serviceLineId", "active", "sortOrder");

-- CreateIndex
CREATE INDEX "Lead_status_createdAt_idx" ON "Lead"("status", "createdAt");

-- CreateIndex
CREATE INDEX "Lead_serviceLineId_status_idx" ON "Lead"("serviceLineId", "status");

-- CreateIndex
CREATE INDEX "Lead_ownerId_status_idx" ON "Lead"("ownerId", "status");

-- CreateIndex
CREATE INDEX "Lead_phone_idx" ON "Lead"("phone");

-- CreateIndex
CREATE INDEX "StageSet_serviceLineId_active_idx" ON "StageSet"("serviceLineId", "active");

-- CreateIndex
CREATE UNIQUE INDEX "StageSet_serviceLineId_name_key" ON "StageSet"("serviceLineId", "name");

-- CreateIndex
CREATE INDEX "CommTemplate_serviceLineId_idx" ON "CommTemplate"("serviceLineId");

-- CreateIndex
CREATE INDEX "DocRule_serviceLineId_idx" ON "DocRule"("serviceLineId");

-- CreateIndex
CREATE INDEX "SlaRule_serviceLineId_idx" ON "SlaRule"("serviceLineId");

-- AddForeignKey
ALTER TABLE "Product" ADD CONSTRAINT "Product_serviceLineId_fkey" FOREIGN KEY ("serviceLineId") REFERENCES "ServiceLine"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Lead" ADD CONSTRAINT "Lead_ownerId_fkey" FOREIGN KEY ("ownerId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Lead" ADD CONSTRAINT "Lead_convertedById_fkey" FOREIGN KEY ("convertedById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Lead" ADD CONSTRAINT "Lead_serviceLineId_fkey" FOREIGN KEY ("serviceLineId") REFERENCES "ServiceLine"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Lead" ADD CONSTRAINT "Lead_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Lead" ADD CONSTRAINT "Lead_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "Client"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Lead" ADD CONSTRAINT "Lead_caseId_fkey" FOREIGN KEY ("caseId") REFERENCES "LoanCase"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "LoanCase" ADD CONSTRAINT "LoanCase_decidedById_fkey" FOREIGN KEY ("decidedById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "LoanCase" ADD CONSTRAINT "LoanCase_serviceLineId_fkey" FOREIGN KEY ("serviceLineId") REFERENCES "ServiceLine"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "LoanCase" ADD CONSTRAINT "LoanCase_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "StageSet" ADD CONSTRAINT "StageSet_serviceLineId_fkey" FOREIGN KEY ("serviceLineId") REFERENCES "ServiceLine"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "StageItem" ADD CONSTRAINT "StageItem_stageSetId_fkey" FOREIGN KEY ("stageSetId") REFERENCES "StageSet"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SlaRule" ADD CONSTRAINT "SlaRule_serviceLineId_fkey" FOREIGN KEY ("serviceLineId") REFERENCES "ServiceLine"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "DocRule" ADD CONSTRAINT "DocRule_serviceLineId_fkey" FOREIGN KEY ("serviceLineId") REFERENCES "ServiceLine"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CommTemplate" ADD CONSTRAINT "CommTemplate_serviceLineId_fkey" FOREIGN KEY ("serviceLineId") REFERENCES "ServiceLine"("id") ON DELETE SET NULL ON UPDATE CASCADE;

